#!/bin/sh

export PROGNAME=$0

export CLASSPATH=

export KAAZING_LIBDIR=/Users/larry/tibco/webmsgems/4.0/lib
export KAAZING_LIBS=${KAAZING_LIBDIR}/client/java/com.kaazing.gateway.jms.client.jar
export KAAZING_LIBS=${KAAZING_LIBS}:${KAAZING_LIBDIR}/geronimo-jms_1.1_spec-1.1.1.jar
export KAAZING_LIBS=${KAAZING_LIBS}:${KAAZING_LIBDIR}/client/java/com.kaazing.gateway.client.jar
#export KZ_ICF=com.kaazing.gateway.jms.client.JmsInitialContextFactory
#export KZ_URL=ws://localhost:8001/jms

export EMS_LIBDIR=/Users/larry/tibco/ems/8.1/lib
export EMS_LIBS=`echo $EMS_LIBDIR/*.jar | tr " " ":"`
#export EMS_ICF=com.tibco.tibjms.naming.TibjmsInitialContextFactory
#export EMS_URL=tibjmsnaming://localhost:7222

export AMQ_LIBS=/usr/local/Cellar/activemq/5.9.1/libexec/activemq-all-5.9.1.jar

usage()
{
  echo "Usage: $0 [ -ems | -twm ] [ other options ]"
}

if [ $# -gt 0 ]; then
  case $1 in
  	-amq )
	  shift
	  CMD="java -cp .:../bin:$AMQ_LIBS $PROGNAME $*"
	  echo Executing $CMD
	  $CMD
	  ;;
  	-ems )
	  shift
	  CMD="java -cp .:../bin:$EMS_LIBS $PROGNAME $*"
	  echo Executing $CMD
	  $CMD
	  ;;
	-twm )
	  shift
	  CMD="java -cp .:../bin:$KAAZING_LIBS $PROGNAME $*"
	  echo Executing $CMD
	  $CMD
          ;;
        * )
	  echo default case
	  usage ;;
  esac
else
  usage
fi
